version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hospital-backend
    ports:
      - "5000:80"   # Serve from nginx's port 80
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: hospital-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
